spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: 2025AdmiN2025
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: Im5qY3RyaHRubGt6Y2doYnl1Y3RybS5oYm5i
    access: 3600000
    refresh: 2592000000